# Generated by Django 4.0.2 on 2022-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленное время')),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.ImageField(upload_to=None)),
            ],
        ),
    ]
