# Generated by Django 4.0.2 on 2022-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedcity',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
