# Generated by Django 4.0.2 on 2022-02-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_searchedcity_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
